// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZkfumoGM_DZacdyUzLMzGVWj6axjGHnM',
    appId: '1:306549037017:web:648bd9c84c9f9d2dd56bc8',
    messagingSenderId: '306549037017',
    projectId: 'chat-app-flutter-4b9fd',
    authDomain: 'chat-app-flutter-4b9fd.firebaseapp.com',
    databaseURL: 'https://chat-app-flutter-4b9fd-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-flutter-4b9fd.appspot.com',
    measurementId: 'G-FLXDLYYVKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcjyiLKqzNSrIb1Kus7WHF87Sl9spq3Bw',
    appId: '1:306549037017:android:7cf4a881bf476914d56bc8',
    messagingSenderId: '306549037017',
    projectId: 'chat-app-flutter-4b9fd',
    databaseURL: 'https://chat-app-flutter-4b9fd-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-flutter-4b9fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXO4NcjIkrrnS43y3ll8VDcL20o99wfX8',
    appId: '1:306549037017:ios:e29c2fbc6ef347a7d56bc8',
    messagingSenderId: '306549037017',
    projectId: 'chat-app-flutter-4b9fd',
    databaseURL: 'https://chat-app-flutter-4b9fd-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-flutter-4b9fd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXO4NcjIkrrnS43y3ll8VDcL20o99wfX8',
    appId: '1:306549037017:ios:2a90985f69b9b41cd56bc8',
    messagingSenderId: '306549037017',
    projectId: 'chat-app-flutter-4b9fd',
    databaseURL: 'https://chat-app-flutter-4b9fd-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-flutter-4b9fd.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
